#!/usr/bin/env python
# coding: utf-8

# In[1]:


from zumi.zumi import Zumi
import time

zumi = Zumi()


# In[2]:


zumi.hazard_lights_on()
zumi.forward(speed=75, duration=.2)
zumi.reverse(speed=75, duration=.2)
zumi.forward(speed=75, duration=.2)
zumi.reverse(speed=75, duration=.2)
zumi.forward(speed=75, duration=.2)
zumi.reverse(speed=75, duration=.2)
zumi.forward(speed=75, duration=.2)
zumi.reverse(speed=75, duration=.2)
zumi.forward(speed=75, duration=.2)
zumi.reverse(speed=75, duration=.2)
zumi.forward(speed=75, duration=.2)
zumi.reverse(speed=75, duration=.2)
zumi.forward(speed=75, duration=.2)
zumi.reverse(speed=75, duration=.2)
zumi.forward(speed=75, duration=.2)
zumi.reverse(speed=75, duration=.2)
zumi.forward(speed=75, duration=.2)
zumi.reverse(speed=75, duration=.2)
zumi.forward(speed=75, duration=.2)
zumi.reverse(speed=75, duration=.2)
zumi.forward(speed=75, duration=.2)
zumi.reverse(speed=75, duration=.2)
zumi.forward(speed=75, duration=.2)
zumi.reverse(speed=75, duration=.2)
zumi.forward(speed=75, duration=.2)
zumi.reverse(speed=75, duration=.2)
zumi.forward(speed=75, duration=.2)
zumi.reverse(speed=75, duration=.2)
zumi.forward(speed=75, duration=.2)
zumi.reverse(speed=75, duration=.2)
zumi.forward(speed=75, duration=.2)
zumi.reverse(speed=75, duration=.2)
zumi.forward(speed=75, duration=.2)
zumi.reverse(speed=75, duration=.2)
zumi.forward(speed=75, duration=.2)
zumi.reverse(speed=75, duration=.2)
zumi.forward(speed=75, duration=.2)
zumi.reverse(speed=75, duration=.2)
zumi.forward(speed=75, duration=.2)
zumi.reverse(speed=75, duration=.2)
zumi.forward(speed=75, duration=.2)
zumi.reverse(speed=75, duration=.2)
zumi.forward(speed=75, duration=.2)
zumi.reverse(speed=75, duration=.2)
zumi.forward(speed=75, duration=.2)
zumi.reverse(speed=75, duration=.2)
zumi.forward(speed=75, duration=.2)
zumi.reverse(speed=75, duration=.2)
zumi.reverse(speed=75, duration=.2)
zumi.hazard_lights_off()
zumi.hazard_lights_on()
zumi.turn_left(33, 0.5)
zumi.turn_right(33, 0.5)
zumi.turn_right(33, 0.5)
zumi.turn_left(33, 0.5)
zumi.turn_left(33, 0.5)
zumi.turn_right(33, 0.5)
zumi.turn_right(33, 0.5)
zumi.turn_left(33, 0.5)
zumi.turn_left(33, 0.5)
zumi.turn_right(33, 0.5)
zumi.turn_right(33, 0.5)
zumi.hazard_lights_off()
zumi.hazard_lights_on()
zumi.turn_left(33, 0.5)
zumi.turn_left(33, 0.5)
zumi.turn_right(33, 0.5)
zumi.turn_right(33, 0.5)
zumi.turn_left(33, 0.5)
zumi.turn_left(33, 0.5)
zumi.turn_right(33, 0.5)
zumi.turn_right(33, 0.5)
zumi.hazard_lights_off()
zumi.hazard_lights_on()
zumi.turn_left(33, 0.5)
zumi.turn_left(33, 0.5)
zumi.turn_right(33, 0.5)
zumi.turn_right(33, 0.5)
zumi.turn_left(33, 0.5)
zumi.turn_left(33, 0.5)
zumi.turn_right(33, 0.5)
zumi.turn_right(33, 0.5)
zumi.turn_left(33, 0.5)
zumi.hazard_lights_off()
zumi.turn_right(85, 1.5)
zumi.forward(speed=30, duration =1.5)
zumi.left_u_turn(speed=30, step=45, delay=0)
zumi.forward(speed=30, duration =1.5)
zumi.turn_right(90, 1.5)
zumi.turn_left(90,1.5)
zumi.forward(speed=30, duration =1.5)
zumi.right_u_turn(speed=30, step=45, delay=0)
zumi.forward(speed=30, duration =1.5)
zumi.turn_left(85,1.5)
zumi.left_circle(speed=30, step=5)
zumi.right_circle(speed=30, step=5)
zumi.figure_8(speed=30, step=7, delay=0)
zumi.j_turn(speed=100, step=4, delay=0)
zumi.forward(speed=30, duration =1.5)
zumi.right_u_turn(speed=30, step=45, delay=0)
zumi.hazard_lights_on()
zumi.forward(speed=35, duration=.5)
zumi.reverse(speed=35, duration=.5)
zumi.forward(speed=40, duration=.5)
zumi.reverse(speed=40, duration=.5)
zumi.hazard_lights_off()
zumi.hazard_lights_on()
zumi.forward(speed=45, duration=.5)
zumi.reverse(speed=45, duration=.5)
zumi.forward(speed=50, duration=.4)
zumi.reverse(speed=50, duration=.4)
zumi.forward(speed=55, duration=.4)
zumi.reverse(speed=55, duration=.4)
zumi.forward(speed=60, duration=.3)
zumi.reverse(speed=60, duration=.3)
zumi.forward(speed=65, duration=.3)


# In[ ]:




